[`README.md`] Split the `Usage` section into 'Configuring' and 'Advanced Configuration'
ota-meshi/eslint-plugin-regexp pull request #192
Opened 2021-05-01 17:08 UTC by darkred

I suggest splitting the `Usage` section into 'Configuring' and 'Advanced Configuration',
hoping to make it more convenient for the user
based on https://github.com/RunDevelopment/eslint-plugin-clean-regex/blob/master/README.md
https://github.com/eslint/eslint-plugin-markdown/blob/main/README.md

PS. I'm glad you have joined forces! Great news!

2021-05-01 17:42 UTC, RunDevelopment requested changes
Thank you for this PR @darkred! I like the idea of this but there are a few things that have to be changed.

First and foremost, `README.md` is partially generated. Please run `npm run update` and commit the changes.

I'll continue the review after the CI passes.

2021-05-01 17:52 UTC, darkred commented
I just did it, thanks.

2021-05-01 17:53 UTC, darkred commented
Did I mess up? Should I should revert? It seems so

2021-05-01 18:11 UTC, RunDevelopment commented
Ahhh, how I love npm.... `npm install` isn't deterministic, so you installed the wrong versions of our dependencies. It's just one of those annoying npm things...

Yes, please revert the commit, then use `npm ci` to reinstall the dependencies, and then it should work.

2021-05-01 18:23 UTC, darkred commented
I just did (revert, then `npm ci` and finally `nmp run install`) , 
and it now shows 58 changed .md files:
<details>
<summary>screenshot</summary>

![2021-05-01_212205](https://user-images.githubusercontent.com/723651/116791480-5406ab80-aac3-11eb-9c22-cbf53e03cb7a.jpg)
</details>

Should I do the commit?

2021-05-01 18:33 UTC, RunDevelopment commented
No, please don't commit.

> I am confused.

Oh yeah, me too.

I don't really understand why this happens to you. Please wait a moment while I look into this.

2021-05-01 18:39 UTC, RunDevelopment commented
Nope, it's something on your end. After running `npm run update` on my end, this is what changed:

<details>

![image](https://user-images.githubusercontent.com/20878432/116791812-0ab35d80-aabd-11eb-8be2-c5022916ca96.png)

</details>

All as expected.

---

Looking at your diff screenshot more closely, it seems like our tooling has problems with lines. Our tooling assumes that all files use Unix line ends (LF). Is that the case on your end?

2021-05-01 18:53 UTC, RunDevelopment commented
I just tested it locally on my machine and your problem is most likely caused by Windows line ends. 

I'm sorry, this is our fault. We didn't tell git to always checkout our code as LF. I'll fix that.

2021-05-01 19:06 UTC, RunDevelopment commented
Alright, I just merged the fix. Please sync your fork to get the changes and then checkout this branch again.

2021-05-01 19:18 UTC, darkred commented
I just pressed "Fetch Origin" in GitHub desktop, and there no commits to pull from my `patch-1` branch or `master`.
Is it something more to do?

I am asking because I just tried `npm test` and it completes ok.

2021-05-01 19:36 UTC, darkred commented
And to clarify:

Initially(2 hours ago) I only used github.com to make the PR, i.e. modified the README.md, and made a PR for it, via my browser . 
In other words, initially, I didn't use GitHub Desktop at all, i.e. I didn't fork locally nor run any commands via CLI.

&nbsp;
After seeing the `CI / update` test was failing, 
only then I cloned my fork locally, and then I tried all these CLI commands you suggested.

&nbsp;
And if you look at the changes, they were not only whitespace, but actual changes all irrelevant to my PR:

<details>
<summary>screen capture</summary>

![](https://user-images.githubusercontent.com/723651/116792144-903c0b00-aac7-11eb-80d5-2269b25df1c0.gif)
</details>

2021-05-01 20:24 UTC, RunDevelopment commented
Don't worry, I'm not blaming you. All of this really shouldn't be so difficult.

> I just pressed "Fetch Origin" in GitHub Desktop

No, that's not enough. I synced and updated your PR branch for you so the CI passes for now. If you're interested in how to that, here's [a guide by GitHub](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork).

I'll review now.

2021-05-01 20:58 UTC, RunDevelopment requested changes

2021-05-01 20:58 UTC, RunDevelopment commented on README.md
> +## :book: Configuring
I think that section should still be called "Usage".

```suggestion
## :book: Usage
```

2021-05-01 20:58 UTC, RunDevelopment commented on README.md
> +    rules: {
Let's keep the quoting consistent.

```suggestion
    "rules": {
```

2021-05-01 20:58 UTC, RunDevelopment commented on README.md
> +        'regexp/rule-name': 'error'
```suggestion
        "regexp/rule-name": "error"
```

2021-05-01 20:58 UTC, RunDevelopment commented on README.md
> +*See https://github.com/ota-meshi/eslint-plugin-regexp/blob/master/lib/configs/recommended.ts for details.*
```suggestion
The `regexp/recommended` config enables a subset of [the core rules](#white_check_mark-rules) that should be most useful to most users.
*See https://github.com/ota-meshi/eslint-plugin-regexp/blob/master/lib/configs/recommended.ts for more details.*
```

2021-05-01 20:58 UTC, RunDevelopment commented on README.md
> +Override/add specific rules settings. *See also: [http://eslint.org/docs/user-guide/configuring](http://eslint.org/docs/user-guide/configuring)*.
I have a problem with the word "settings". Settings are a different concept in ESLint, so we should use a different word here.

```suggestion
Override/add specific rules configurations. *See also: [http://eslint.org/docs/user-guide/configuring](http://eslint.org/docs/user-guide/configuring)*.
```

2021-05-01 21:06 UTC, darkred commented
Thank you for the review. I committed all your suggested changes.

2021-05-01 21:28 UTC, merged

2021-05-01 21:29 UTC, RunDevelopment commented
Thank you for contributing @darkred!

2021-05-01 21:30 UTC, darkred commented
Glad I was able to contribute!

2021-05-06 17:11 UTC, darkred commented
// offtopic

> All of this really shouldn't be so difficult.

https://twitter.com/natfriedman/status/1390350476009377795

> Working on a fix, and notice your fork is behind? Now, you can sync from the parent with just a single click in the GitHub UI. > 👇
> 
> Hope you like it! 🌟

Finally !! 😎👍

// offtopic