Add option to allow only partial use to the `allowTop` option of `regexp/no-useless-non-capturing-group` rule.
ota-meshi/eslint-plugin-regexp pull request #215
Opened 2021-05-28 23:48 UTC by ota-meshi

Related to https://github.com/ota-meshi/eslint-plugin-regexp/issues/181#issuecomment-838271791.

2021-05-30 12:07 UTC, RunDevelopment requested changes
Thank you @ota-meshi!

Two minor things but apart from that good to go.

2021-05-30 12:07 UTC, RunDevelopment commented on lib/rules/no-useless-non-capturing-group.ts
> +            let isIgnore: (gNode: Group) => boolean
Pedantic nit...

```suggestion
            let isIgnored: (gNode: Group) => boolean
```

2021-05-30 12:07 UTC, RunDevelopment commented on lib/rules/no-useless-non-capturing-group.ts
> +                    isIgnore = isTopLevel
I would prefer this to be more conservative. The usage might be `UsageOfPattern.unknown`. If we don't know the usage, then we shouldn't assume that it's okay to remove the top-level group.

```suggestion
                if (usageOfPattern !== UsageOfPattern.whole) {
                    isIgnore = isTopLevel
```

2021-06-01 00:41 UTC, ota-meshi commented
Thank you for your review! I updated it, so could you check it again?

2021-06-01 00:43 UTC, ota-meshi commented
I noticed that I haven't changed about autofix yet. I will fix it again.

2021-06-01 00:55 UTC, ota-meshi commented
>I noticed that I haven't changed about autofix yet. I will fix it again.

I fixed it.

2021-06-01 10:49 UTC, merged

2021-06-01 10:49 UTC, RunDevelopment commented
Thank you @ota-meshi!