Add `regexp/no-misleading-unicode-character` rule
ota-meshi/eslint-plugin-regexp pull request #332
Opened 2021-09-20 11:09 UTC by RunDevelopment

Relates to #325.

This adds the `no-misleading-unicode-character` rule as discussed [here](https://github.com/ota-meshi/eslint-plugin-regexp/issues/325#issuecomment-922271310). There are a few differences to ESLint's `no-misleading-character-class` rule:

- We support misleading quantifiers.
- Reports are auto-fixed.
- Reports are much more granular.
- We ignore characters using escape sequences. We only care about visible characters, not hexadecimal escapes. E.g. ESLint's rule will report `/[\ud83d\udc4d]/`, we won't.

One open question: Should we auto-fix?
Right now, the rule will auto-fix wherever possible using groups. We essentially assume that people want to treat graphemes as single units. That is a very reasonable assumption but an assumption nonetheless.

2021-09-21 00:32 UTC, ota-meshi requested changes

2021-09-21 00:32 UTC, ota-meshi commented on lib/rules/no-misleading-unicode-character.ts
> +        ccRaw = ccRaw.slice(0, start) + ccRaw.slice(end)
Maybe we need to do the following:

```suggestion
        ccRaw = ccRaw.slice(0, start - cc.start) + ccRaw.slice(end - cc.start)
```

I found that it couldn't be autofixed well in the following cases:

```js
/[竈門禰󠄀豆子]|[煉󠄁獄杏寿郎]/
```

2021-09-21 01:16 UTC, ota-meshi commented
> Should we auto-fix?

I personally find auto-fix useful for me, but I think it may be better for some language native users not to auto-fix.
I think it may be better to move to the Suggestion API to avoid confusion. Or add `fixable` option like `no-unused-capturing-group`.

2021-09-21 11:48 UTC, RunDevelopment commented
I like the `fixable` option.

2021-09-22 01:40 UTC, ota-meshi approved these changes
LGTM! Thank you!

2021-09-22 01:40 UTC, merged