Fix crash when used with TypeScript
ota-meshi/eslint-plugin-regexp pull request #379
Opened 2021-11-22 04:01 UTC by ota-meshi

fixes #378

2021-11-22 10:33 UTC, RunDevelopment requested changes
Thank you for the fix @ota-meshi!

2021-11-22 10:33 UTC, RunDevelopment commented on lib/utils/type-tracker/index.ts
> +        return checker?.typeToString(tsType) as TypeInfo
[`?.` always returns `undefined` if the lhs is nullish](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) (not obvious IMO, but that's how it is). `undefined` isn't compatible with a return type of `TypeInfo | null`.

```suggestion
        return checker ? (checker.typeToString(tsType) as TypeInfo) : null
```

2021-11-23 02:16 UTC, ota-meshi commented
Thank you for pointing out and suggestions! I changed this PR.

2021-11-23 09:06 UTC, RunDevelopment approved these changes

2021-11-23 09:06 UTC, merged